name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Frontend build steps
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.16.0'

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    # Backend build steps
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.10'

    - name: Install backend dependencies
      working-directory: backend
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Test backend
      working-directory: backend
      run: |
        . venv/bin/activate
        pytest

    # Docker build and push
    - name: Build Docker image for backend
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/aenergy-backend:latest ./backend

    - name: Build Docker image for frontend
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/aenergy-frontend:latest ./frontend

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image for backend
      run: docker push ${{ secrets.DOCKER_USERNAME }}/aenergy-backend:latest

    - name: Push Docker image for frontend
      run: docker push ${{ secrets.DOCKER_USERNAME }}/aenergy-frontend:latest
